### ISSUE TITLE
Accordion demo isn't a true accordion

### ISSUE THREAD

**Issue by Tyler-H** [you-dont-need/You-Dont-Need-JavaScript#16]
In an accordion menu, only one "section" opens at a time (this mimics the musical instrument which stretches open one part the bellows at a time). In your demo, opening a second or third section does not close the previously-opened section.

**Comment by NamPNQ** [comment]
I found a demo in #15, it's awesome

**Comment by Tyler-H** [comment]
Not ideal, since you have to have at least one item open at all times in that demo

**Comment by ShirtlessKirk** [comment]
The bellows of an accordion open and close all parts at the same time. This reduces wear on one part should the player not fully open and close them.

**Comment by Calefornia** [comment]
I feel like we've got two separate issues: 1) designing for simplicity, and 2) avoiding Javascript.

JS is necessary in certain cases, but if the goal is to avoid it at all costs, these alternatives need not be perfect or true replacements for JS capabilities. However, if they increase complexity, it seems foolhardy to shun JS at all costs.

As mentioned in #14, there needs to be some clarification for scenarios that are not worth using CSS or JS. I'm playing around with personal web stuff and just want enough styling to change background colors and make text look nice. A few animations or other tricks from this project will be fun, so I appreciate having this resource.

I'd like to minimize my usage of javascript because I don't want to invest a lot of time learning it, and I don't want to make a website that needs a lot of code to function. It's like alcohol -- too much, and you get a headache. That goes for js or css, and for a personal blog, you really don't need much of anything...
